name 'factorio'
maintainer 'Arsh Chauhan'
maintainer_email 'achauhan@alaska.edu'
license 'MIT'
description 'Installs/Configures factorio'
version '0.1.0'
chef_version '>= 14.0'
supports 'ubuntu', '>=18.04'

issues_url 'https://github.com/Arsh25/factorio_chef/issues'
source_url 'https://github.com/Arsh25/factorio_chef'
